services:
  login-service:
    build: ./services/login
    ports:
      - "3000:3000"
    environment:
      - DB_SOCKET_PATH=/cloudsql/lexical-task-452420-s2:us-central1:ms-login
      - DB_HOST=${DB_HOST}            # Dirección IP de Google Cloud SQL
      - DB_PORT=${DB_PORT}            # Puerto de MySQL
      - DB_USER=${DB_USER}            # Usuario de la base de datos
      - DB_PASSWORD=${DB_PASSWORD}    # Contraseña de la base de datos
      - DB_NAME=${DB_NAME}            # Nombre de la base de datos
      - JWT_SECRET=${JWT_SECRET}      # Clave secreta para JWT
    restart: unless-stopped  # Asegura que el contenedor se reinicie si falla
