services:
  login-service:
    build: ./services/login
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - my_global_network  # Conectamos a la red externa
    restart: unless-stopped

networks:
  my_global_network:
    external: true  # Usamos la red creada manualmente